/**
 * Canonical Polish URL paths for the application.
 */
export const routes = {
  home: '/',
  logowanie: '/logowanie',
  rejestracja: '/rejestracja',
  rejestracjaWyborWeryfikacji: '/rejestracja/wybor-weryfikacji',
  zapomnianeHaslo: '/zapomniane-haslo',
  konto: '/konto',
  wiadomosci: '/wiadomosci',
  zapisaneZgloszenia: '/zapisane-zgloszenia',
  wykonawcy: '/wykonawcy',
  zarzadcy: '/zarzadcy',
  zlecenia: '/zlecenia',
  zlecenie: (id: string) => `/zlecenia/${id}` as const,
  wykonawca: (id: string) => `/wykonawcy/${id}` as const,
  zarzadca: (id: string) => `/zarzadcy/${id}` as const,
  dodajZlecenie: '/dodaj-zlecenie',
  dodajKonkurs: '/dodaj-konkurs',
  dodajKonkursEdycja: (id: string) => `/dodaj-konkurs/${id}` as const,
  dodajPrzetarg: '/dodaj-przetarg',
  dodajPrzetargEdycja: (id: string) => `/dodaj-przetarg/${id}` as const,
  tworzeniePrzetargu: '/tworzenie-przetargu',
  wyborTypuZlecenia: '/wybor-typu-zlecenia',
  wyborTypuKonta: '/wybor-typu-konta',
  uzupelnianieProfilu: '/uzupelnianie-profilu',
  weryfikacja: '/weryfikacja',
  powitanie: '/powitanie',
  samouczek: '/samouczek',
  wdrozenie: '/wdrozenie',
  konsultacjaEksperta: '/konsultacja-eksperta',
  regulamin: '/regulamin',
  politykaPrywatnosci: '/polityka-prywatnosci',
  panelWykonawcy: '/panel-wykonawcy',
  panelWykonawcyAplikacje: '/panel-wykonawcy/aplikacje',
  panelWykonawcyPanel: '/panel-wykonawcy/panel',
  panelWykonawcyUlubione: '/panel-wykonawcy/ulubione',
  panelWykonawcyOceny: '/panel-wykonawcy/oceny',
  panelWykonawcyCennik: '/panel-wykonawcy/cennik',
  panelWykonawcyProjekty: '/panel-wykonawcy/projekty',
  panelWykonawcyZamowienia: '/panel-wykonawcy/zamowienia',
  panelZarzadcy: '/panel-zarzadcy',
  panelZarzadcyZlecenia: '/panel-zarzadcy/zlecenia',
  panelZarzadcyWykonawcy: '/panel-zarzadcy/wykonawcy',
  panelZarzadcyPrzetargi: '/panel-zarzadcy/przetargi',
  panelZarzadcyKonkursy: '/panel-zarzadcy/konkursy',
  panelZarzadcyZgloszenia: '/panel-zarzadcy/zgloszenia',
  panelZarzadcyZamowienia: '/panel-zarzadcy/zamowienia',
  panelZarzadcyOcenaZgloszen: '/panel-zarzadcy/ocena-zgloszen',
  administracja: '/administracja',
  administracjaWeryfikacja: '/administracja/weryfikacja',
  administracjaWeryfikacjaUzytkownik: (userId: string) =>
    `/administracja/weryfikacja/${userId}` as const,
  administracjaUstawienia: '/administracja/ustawienia',
  administracjaOferty: '/administracja/oferty',
  administracjaOgloszenia: '/administracja/ogloszenia',
  authAktualizacjaHasla: '/auth/aktualizacja-hasla',
  kontoDokumenty: '/konto?tab=documents',
} as const

export type AppRoute = (typeof routes)[keyof typeof routes]
