import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '../../types/database';

export interface PendingVerificationRow {
  userId: string;
  firstName: string;
  lastName: string;
  userType: string;
  verificationSubmittedAt: string;
  companyId: string | null;
  companyName: string | null;
  companyType: string | null;
}

export interface RejectedVerificationRow {
  userId: string;
  firstName: string;
  lastName: string;
  userType: string;
  companyId: string | null;
  companyName: string | null;
  companyType: string | null;
  decidedAt: string;
  reason: string | null;
}

export interface ApprovedVerificationRow {
  userId: string;
  firstName: string;
  lastName: string;
  userType: string;
  companyId: string | null;
  companyName: string | null;
  companyType: string | null;
  decidedAt: string;
}

export interface VerificationDocumentEntry {
  key: string;
  label: string;
  path: string;
  filename: string;
  /**
   * ISO timestamp parsed from the storage filename's `Date.now()` prefix
   * (see `submitVerificationDocumentsAction`). Null when the prefix can't
   * be parsed — typically for legacy paths uploaded before this convention.
   */
  uploadedAt: string | null;
  viewUrl: string | null;
  downloadUrl: string | null;
  error?: string;
}

export interface DocumentReview {
  status: 'approved' | 'rejected';
  reason: string | null;
  reviewedAt: string;
  reviewedBy: string;
}

export type DocumentReviewMap = Record<string, DocumentReview>;

const VERIFICATION_BUCKET = 'verification-documents';

const DOC_LABELS: Record<string, string> = {
  company_registration: 'Wypis z KRS / CEIDG',
  insurance: 'Polisa ubezpieczeniowa',
  certifications: 'Certyfikaty',
  references: 'Referencje',
  management_license: 'Licencja zarządcy',
  management_contracts: 'Umowy zarządcze',
  oc_policy_scan: 'Polisa OC',
};

export function verificationDocumentLabel(key: string): string {
  return DOC_LABELS[key] ?? key;
}

function logSupabaseError(label: string, error: unknown): void {
  if (error && typeof error === 'object') {
    const e = error as { message?: string; details?: string; hint?: string; code?: string };
    console.error(label, {
      message: e.message,
      details: e.details,
      hint: e.hint,
      code: e.code,
    });
  } else {
    console.error(label, error);
  }
}

function appendDownloadParam(signedUrl: string, filename: string): string {
  const separator = signedUrl.includes('?') ? '&' : '?';
  return `${signedUrl}${separator}download=${encodeURIComponent(filename)}`;
}

/**
 * Filenames generated by `submitVerificationDocumentsAction` are prefixed with
 * `${Date.now()}-` so we can recover the upload time without round-tripping to
 * Storage object metadata. Returns null when the prefix is missing or invalid.
 */
function parseUploadedAtFromFilename(filename: string): string | null {
  const match = filename.match(/^(\d{10,16})-/);
  if (!match) return null;
  const ms = Number(match[1]);
  if (!Number.isFinite(ms) || ms <= 0) return null;
  // Reject obviously bogus values (year < 2001 or > +50y from now).
  const fiftyYearsMs = 50 * 365 * 24 * 60 * 60 * 1000;
  const lowerBound = Date.UTC(2001, 0, 1);
  const upperBound = Date.now() + fiftyYearsMs;
  if (ms < lowerBound || ms > upperBound) return null;
  return new Date(ms).toISOString();
}

/**
 * Build view + download signed URLs for a map of doc key -> storage path.
 */
export async function getVerificationDocumentSignedUrls(
  supabase: SupabaseClient<Database>,
  paths: Record<string, string>
): Promise<VerificationDocumentEntry[]> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;
  const entries: VerificationDocumentEntry[] = [];

  for (const [key, path] of Object.entries(paths)) {
    if (!path || typeof path !== 'string') {
      continue;
    }
    const filename = path.split('/').pop() ?? key;
    const uploadedAt = parseUploadedAtFromFilename(filename);
    const { data, error } = await sb.storage
      .from(VERIFICATION_BUCKET)
      .createSignedUrl(path, 3600);

    if (error || !data?.signedUrl) {
      entries.push({
        key,
        label: verificationDocumentLabel(key),
        path,
        filename,
        uploadedAt,
        viewUrl: null,
        downloadUrl: null,
        error: (error as { message?: string } | null)?.message ?? 'Nie udało się wygenerować linku.',
      });
      continue;
    }

    entries.push({
      key,
      label: verificationDocumentLabel(key),
      path,
      filename,
      uploadedAt,
      viewUrl: data.signedUrl,
      downloadUrl: appendDownloadParam(data.signedUrl, filename),
    });
  }

  return entries;
}

/**
 * Per-document admin review annotations stored on `user_profiles`. Returns an
 * empty map for users without any reviews.
 */
export async function fetchVerificationDocumentReviews(
  supabase: SupabaseClient<Database>,
  subjectUserId: string
): Promise<DocumentReviewMap> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;
  const { data, error } = await sb
    .from('user_profiles')
    .select('verification_document_reviews')
    .eq('id', subjectUserId)
    .maybeSingle();

  if (error) {
    logSupabaseError('fetchVerificationDocumentReviews', error);
    return {};
  }

  return (data?.verification_document_reviews as DocumentReviewMap | null | undefined) ?? {};
}

/**
 * Latest `verification_decisions.created_at` for a single user (any decision
 * type), used by the admin detail page to highlight which documents were
 * (re)uploaded after the most recent decision.
 */
export async function fetchLatestDecisionAtForUser(
  supabase: SupabaseClient<Database>,
  subjectUserId: string
): Promise<string | null> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;
  const { data, error } = await sb
    .from('verification_decisions')
    .select('created_at')
    .eq('subject_user_id', subjectUserId)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (error) {
    logSupabaseError('fetchLatestDecisionAtForUser', error);
    return null;
  }
  return (data?.created_at as string | null) ?? null;
}

/**
 * Users who submitted verification docs and are not yet verified on profile / primary company.
 */
export async function fetchPendingVerificationQueue(
  supabase: SupabaseClient<Database>
): Promise<PendingVerificationRow[]> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;

  const { data: profiles, error } = await sb
    .from('user_profiles')
    .select(
      `
      id,
      first_name,
      last_name,
      user_type,
      verification_submitted_at,
      verification_document_paths,
      is_verified,
      user_companies (
        is_primary,
        company_id,
        companies (
          id,
          name,
          type,
          is_verified
        )
      )
    `
    )
    .not('verification_submitted_at', 'is', null)
    .eq('is_verified', false)
    .order('verification_submitted_at', { ascending: true });

  if (error) {
    logSupabaseError('fetchPendingVerificationQueue', error);
    return [];
  }

  const rows: PendingVerificationRow[] = [];

  for (const p of profiles ?? []) {
    const ucs = (p.user_companies ?? []) as Array<{
      is_primary?: boolean;
      companies?: { id?: string; name?: string; type?: string; is_verified?: boolean };
    }>;
    const primary = ucs.find((uc) => uc.is_primary) ?? ucs[0];
    const company = primary?.companies;
    if (company?.is_verified) {
      continue;
    }

    rows.push({
      userId: p.id as string,
      firstName: (p.first_name as string) ?? '',
      lastName: (p.last_name as string) ?? '',
      userType: (p.user_type as string) ?? '',
      verificationSubmittedAt: p.verification_submitted_at as string,
      companyId: company?.id ?? null,
      companyName: company?.name ?? null,
      companyType: company?.type ?? null,
    });
  }

  return rows;
}

interface DecisionWithProfile {
  subject_user_id: string;
  decision: string;
  reason: string | null;
  created_at: string;
}

/**
 * Returns the latest decision per user (independent of decision type).
 */
async function fetchLatestDecisions(
  supabase: SupabaseClient<Database>
): Promise<Map<string, DecisionWithProfile>> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;
  const { data, error } = await sb
    .from('verification_decisions')
    .select('subject_user_id, decision, reason, created_at')
    .order('created_at', { ascending: false })
    .limit(2000);

  if (error) {
    logSupabaseError('fetchLatestDecisions', error);
    return new Map();
  }

  const latest = new Map<string, DecisionWithProfile>();
  for (const d of (data ?? []) as DecisionWithProfile[]) {
    if (!latest.has(d.subject_user_id)) {
      latest.set(d.subject_user_id, d);
    }
  }
  return latest;
}

interface ProfileWithCompany {
  id: string;
  first_name: string | null;
  last_name: string | null;
  user_type: string | null;
  is_verified: boolean | null;
  user_companies?: Array<{
    is_primary?: boolean;
    companies?: { id?: string; name?: string; type?: string };
  }>;
}

async function fetchProfilesByIds(
  supabase: SupabaseClient<Database>,
  ids: string[]
): Promise<Map<string, ProfileWithCompany>> {
  if (ids.length === 0) return new Map();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;
  const { data, error } = await sb
    .from('user_profiles')
    .select(
      `
      id, first_name, last_name, user_type, is_verified,
      user_companies ( is_primary, companies ( id, name, type ) )
    `
    )
    .in('id', ids);

  if (error) {
    logSupabaseError('fetchProfilesByIds', error);
    return new Map();
  }

  const map = new Map<string, ProfileWithCompany>();
  for (const p of (data ?? []) as ProfileWithCompany[]) {
    map.set(p.id, p);
  }
  return map;
}

function pickCompany(profile: ProfileWithCompany | undefined) {
  const ucs = profile?.user_companies ?? [];
  const primary = ucs.find((uc) => uc.is_primary) ?? ucs[0];
  return primary?.companies ?? null;
}

export async function fetchRejectedVerificationQueue(
  supabase: SupabaseClient<Database>
): Promise<RejectedVerificationRow[]> {
  const latest = await fetchLatestDecisions(supabase);
  const rejectedIds: string[] = [];
  for (const [uid, dec] of latest.entries()) {
    if (dec.decision === 'rejected') rejectedIds.push(uid);
  }

  const profiles = await fetchProfilesByIds(supabase, rejectedIds);

  const rows: RejectedVerificationRow[] = [];
  for (const uid of rejectedIds) {
    const profile = profiles.get(uid);
    if (!profile) continue;
    if (profile.is_verified) continue;
    const decision = latest.get(uid)!;
    const company = pickCompany(profile);
    rows.push({
      userId: profile.id,
      firstName: profile.first_name ?? '',
      lastName: profile.last_name ?? '',
      userType: profile.user_type ?? '',
      companyId: company?.id ?? null,
      companyName: company?.name ?? null,
      companyType: company?.type ?? null,
      decidedAt: decision.created_at,
      reason: decision.reason ?? null,
    });
  }

  rows.sort((a, b) => b.decidedAt.localeCompare(a.decidedAt));
  return rows;
}

export async function fetchApprovedVerificationQueue(
  supabase: SupabaseClient<Database>
): Promise<ApprovedVerificationRow[]> {
  const latest = await fetchLatestDecisions(supabase);
  const approvedIds: string[] = [];
  for (const [uid, dec] of latest.entries()) {
    if (dec.decision === 'approved') approvedIds.push(uid);
  }

  const profiles = await fetchProfilesByIds(supabase, approvedIds);

  const rows: ApprovedVerificationRow[] = [];
  for (const uid of approvedIds) {
    const profile = profiles.get(uid);
    if (!profile) continue;
    const decision = latest.get(uid)!;
    const company = pickCompany(profile);
    rows.push({
      userId: profile.id,
      firstName: profile.first_name ?? '',
      lastName: profile.last_name ?? '',
      userType: profile.user_type ?? '',
      companyId: company?.id ?? null,
      companyName: company?.name ?? null,
      companyType: company?.type ?? null,
      decidedAt: decision.created_at,
    });
  }

  rows.sort((a, b) => b.decidedAt.localeCompare(a.decidedAt));
  return rows;
}

export async function fetchAdminNotesForUser(
  supabase: SupabaseClient<Database>,
  subjectUserId: string
): Promise<Array<{ id: string; body: string; created_at: string; author_id: string }>> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sb = supabase as any;
  const { data, error } = await sb
    .from('admin_user_notes')
    .select('id, body, created_at, author_id')
    .eq('subject_user_id', subjectUserId)
    .order('created_at', { ascending: false });

  if (error) {
    logSupabaseError('fetchAdminNotesForUser', error);
    return [];
  }

  return (data ?? []) as Array<{ id: string; body: string; created_at: string; author_id: string }>;
}
